-- Pełne załadowanie danych ligowych z db/import/*.csv (świeże eksporty).
-- Uruchamiane wewnątrz kontenera postgres: pliki CSV skopiowane do /tmp/import/.
-- COPY jest server-side, więc pliki muszą być w tym samym kontenerze co serwer bazy.

BEGIN;

-- Pozwól wstawić jawne ID do kolumn IDENTITY (zachowujemy oryginalne klucze i FK).
ALTER TABLE liga_wystepowanie_w_regatach ALTER COLUMN id_wystepowania SET GENERATED BY DEFAULT;
ALTER TABLE liga_miejsca                 ALTER COLUMN id_miejsca      SET GENERATED BY DEFAULT;
ALTER TABLE liga_wynikregatmanual        ALTER COLUMN id             SET GENERATED BY DEFAULT;

-- Czyścimy komplet (dzieci przez CASCADE).
TRUNCATE
  liga_miejsca,
  liga_wynikregatmanual,
  liga_wystepowanie_w_regatach,
  liga_wyscigi,
  liga_regaty,
  liga_klubwariant,
  liga_zawodnik,
  liga_zestawienieklubow
  RESTART IDENTITY CASCADE;

-- Ładowanie rodzice -> dzieci. HEADER true pomija wiersz nagłówka; kolejność kolumn = jak w CSV.
COPY liga_zestawienieklubow (id_zestawienia_klubow, nazwa)
  FROM '/tmp/import/liga_ZestawienieKlubow.csv' WITH (FORMAT csv, HEADER true);

COPY liga_klubwariant (id_wariantu_klubu, skrot, nazwa, id_zestawienia_klubow)
  FROM '/tmp/import/liga_KlubWariant.csv' WITH (FORMAT csv, HEADER true);

COPY liga_zawodnik (id_zawodnika, imie, nazwisko, email, pozycja_na_lodce, data_wstapienia_do_plz, numer_licencji, numer_ubezpieczenia)
  FROM '/tmp/import/liga_Zawodnik.csv' WITH (FORMAT csv, HEADER true);

COPY liga_regaty (id_regat, nazwa, liga_poziom, miasto, numer_rundy, rok)
  FROM '/tmp/import/liga_Regaty.csv' WITH (FORMAT csv, HEADER true);

COPY liga_wyscigi (id_wyscigu, id_regat, numer_wyscigu, finalowy)
  FROM '/tmp/import/liga_Wyscigi.csv' WITH (FORMAT csv, HEADER true);

COPY liga_wystepowanie_w_regatach (id_wystepowania, id_zawodnika, id_regat, id_wariantu_klubu, wynikwregatach, trening)
  FROM '/tmp/import/liga_Wystepowanie_w_regatach.csv' WITH (FORMAT csv, HEADER true);

COPY liga_miejsca (id_miejsca, id_wyscigu, id_wariantu_klubu, zajete_miejsce, kary, numer_lodki)
  FROM '/tmp/import/liga_Miejsca.csv' WITH (FORMAT csv, HEADER true);

COPY liga_wynikregatmanual (id, regaty, id_wariantu_klubu, miejscewregatach)
  FROM '/tmp/import/liga_WynikRegatManual.csv' WITH (FORMAT csv, HEADER true);

-- Ustaw sekwencje IDENTITY na MAX(id)+1, żeby przyszłe wstawienia nie kolidowały.
SELECT setval(pg_get_serial_sequence('liga_wystepowanie_w_regatach','id_wystepowania'),
              COALESCE((SELECT MAX(id_wystepowania) FROM liga_wystepowanie_w_regatach), 1));
SELECT setval(pg_get_serial_sequence('liga_miejsca','id_miejsca'),
              COALESCE((SELECT MAX(id_miejsca) FROM liga_miejsca), 1));
SELECT setval(pg_get_serial_sequence('liga_wynikregatmanual','id'),
              COALESCE((SELECT MAX(id) FROM liga_wynikregatmanual), 1));

COMMIT;

-- Kontrola liczby wierszy.
SELECT 'zestawienieklubow' AS tabela, COUNT(*) FROM liga_zestawienieklubow
UNION ALL SELECT 'klubwariant', COUNT(*) FROM liga_klubwariant
UNION ALL SELECT 'zawodnik', COUNT(*) FROM liga_zawodnik
UNION ALL SELECT 'regaty', COUNT(*) FROM liga_regaty
UNION ALL SELECT 'wyscigi', COUNT(*) FROM liga_wyscigi
UNION ALL SELECT 'wystepowanie', COUNT(*) FROM liga_wystepowanie_w_regatach
UNION ALL SELECT 'miejsca', COUNT(*) FROM liga_miejsca
UNION ALL SELECT 'wynikregatmanual', COUNT(*) FROM liga_wynikregatmanual;
